import { useState } from "react";
import { ArrowRight, BellRing, Cpu, Gauge, Menu, ShieldCheck, Smartphone, Truck, Wifi, X } from "lucide-react";

const appUrl = "https://guardiangass.yvonnekimera2.workers.dev/";
const screens = [
  { id: "home", label: "Household overview", image: "/assets/dashboard.png", title: "A calm household overview", copy: "The household sees the approximate gas remaining, current cylinder weight, safety state, selected refill provider, and usage history without having to interpret raw sensor data." },
  { id: "refill", label: "Household refills", image: "/assets/refills.png", title: "Refills, without the chase", copy: "Households can select a provider, request a refill, and keep track of its status from the same workspace that shows the cylinder condition." },
  { id: "technician", label: "Technician operations", image: "/assets/technician-refills.png", title: "A visible refill workflow", copy: "Technicians receive assigned requests and progress them from pending to accepted, in transit, completed, or cancelled—giving the household a reliable record of what is happening." },
  { id: "admin", label: "Administrator overview", image: "/assets/admin-overview.png", title: "Platform-wide oversight", copy: "Administrators can see platform users, households, cylinders, open refills, and safety conditions that need attention." },
];
const steps = [
  { icon: Gauge, num: "01", title: "Measure", text: "A load cell measures the cylinder’s weight. An MQ-2 sensor checks the air around it for leaked gas." },
  { icon: Cpu, num: "02", title: "Interpret", text: "The ESP32 processes readings, drives the OLED, LEDs and buzzer, and prepares a secure update." },
  { icon: Wifi, num: "03", title: "Connect", text: "Lumora turns the reading into gas level, safety, history, and estimated depletion information." },
  { icon: BellRing, num: "04", title: "Respond", text: "The household gets alerts and can request a refill. Other roles get the views relevant to them." },
];
function Logo(){return <a className="logo" href="#top"><i><Gauge size={19}/></i><span><b>Lumora</b><small>GAS, MADE VISIBLE</small></span></a>}
export default function App(){
 const [active,setActive]=useState(screens[0]); const [menu,setMenu]=useState(false);
 return <div className="site" id="top"><header><Logo/><nav className={menu?"show":""}>{[["Challenge","challenge"],["System","system"],["Roles","roles"],["Screens","screens"]].map(([x,id])=><a href={`#${id}`} onClick={()=>setMenu(false)} key={id}>{x}</a>)}</nav><a className="open-app" href={appUrl}>Open working system <ArrowRight size={14}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header><main>
 <section className="hero layout"><div><p className="kicker">Makerere University · Practical Skills Project</p><h1>Making LPG use <em>visible, safer,</em> and easier to plan.</h1><p className="intro">Lumora is a smart LPG monitoring and gas leakage detection system. It brings the physical cylinder, the household, the refill provider, and the administrator into one connected workflow.</p><div className="actions"><a className="button" href="#system">Explore the system <ArrowRight size={17}/></a><a className="plain" href={appUrl}>Visit the live app ↗</a></div></div><aside><span>PROJECT BRIEF</span><dl><div><dt>Hardware</dt><dd>ESP32 · load cell · MQ-2 sensor</dd></div><div><dt>Purpose</dt><dd>Monitor LPG levels and warn of possible leaks</dd></div><div><dt>Platform</dt><dd>Alerts, insights, and refill coordination</dd></div></dl></aside></section>
 <section id="challenge" className="section layout split"><div><p className="kicker">01 / The challenge</p><h2>When gas runs out, the problem has already arrived.</h2></div><div className="copy"><p>LPG is widely used for cooking, but the amount remaining in a cylinder is usually uncertain until the flame stops. It is an inconvenience for any household and can be particularly difficult when a refill cannot be arranged immediately.</p><p>Gas leakages create an even greater concern. Lumora is designed around early awareness: a meaningful local signal at the cylinder and a clear notification for the people responsible for it.</p></div></section>
 <section id="system" className="section dark"><div className="layout"><p className="kicker">02 / The system</p><h2>A local device and a web platform, each doing the job it is best placed to do.</h2><p className="system-copy">The device stays with the cylinder. It provides a live measurement and immediate feedback in the home. The platform makes that information accessible from elsewhere, maintains the history, and connects the household with the refill service.</p><div className="steps">{steps.map(({icon:Icon,num,title,text})=><article key={num}><span>{num}</span><Icon size={25}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section id="roles" className="section layout"><p className="kicker">03 / People and roles</p><h2>Three workspaces. One shared source of truth.</h2><div className="roles"><article><Smartphone/><div><span>HOUSEHOLD</span><h3>Understand and act at home.</h3></div><p>Pairs the device, monitors cylinder status, receives alerts, chooses a preferred provider, and makes manual or automatic refill requests.</p></article><article><Truck/><div><span>REFILL PROVIDER / TECHNICIAN</span><h3>Turn a request into a completed refill.</h3></div><p>Receives assigned requests, reviews customer details, and progresses each refill through accepted, in transit, completed, or cancelled.</p></article><article><ShieldCheck/><div><span>ADMINISTRATOR</span><h3>Keep the whole platform accountable.</h3></div><p>Manages users, cylinders and devices while monitoring open refill activity and safety conditions across Lumora.</p></article></div></section>
 <section id="screens" className="section dark"><div className="layout"><div className="screen-title"><div><p className="kicker">04 / The working platform</p><h2>Designed for the people using it.</h2></div></div><div className="tabs">{screens.map(s=><button key={s.id} className={active.id===s.id?"active":""} onClick={()=>setActive(s)}>{s.label}</button>)}</div><div className="viewer"><div className="viewer-copy"><span>WORKSPACE</span><h3>{active.title}</h3><p>{active.copy}</p><a href={appUrl}>Open the working system <ArrowRight size={15}/></a></div><img src={active.image} alt={active.label}/></div></div></section>
 <section className="conclusion layout"><p className="kicker">Project conclusion</p><h2>A more predictable relationship with an everyday household essential.</h2><p>Lumora combines monitoring, early safety feedback, and practical refill coordination—so the household has more time to respond before an empty cylinder or possible leak becomes a crisis.</p><a className="button" href={appUrl}>Open the working Lumora system <ArrowRight size={17}/></a></section>
 </main><footer className="layout"><Logo/><span>Smart LPG Monitoring and Gas Leakage Detection System · 2026</span></footer></div>
}
