import React, { useState } from "react";

const appUrl = "https://guardiangass.yvonnekimera2.workers.dev/";
const screens = [
  ["Household overview", "/assets/dashboard.png", "A calm household overview", "The household sees remaining gas, current cylinder weight, safety status, the selected provider, and usage history without having to interpret raw sensor data."],
  ["Household refills", "/assets/refills.png", "Refills, without the chase", "Households can select a provider, request a refill, and keep track of it from the same workspace that shows the cylinder condition."],
  ["Technician operations", "/assets/technician-refills.png", "A visible refill workflow", "Technicians receive assigned requests and progress them from pending to accepted, in transit, completed, or cancelled."],
  ["Administrator overview", "/assets/admin-overview.png", "Platform-wide oversight", "Administrators can see platform users, households, cylinders, open refills, and safety conditions that need attention."],
];
const steps = [
  ["01", "Measure", "A load cell measures the cylinder's weight. An MQ-2 sensor checks the air around it for leaked gas."],
  ["02", "Interpret", "The ESP32 processes readings, drives the OLED, LEDs and buzzer, and prepares a secure update."],
  ["03", "Connect", "Lumora turns the reading into gas level, safety, history, and estimated depletion information."],
  ["04", "Respond", "The household gets alerts and can request a refill. Other roles get the views relevant to them."],
];

function Logo() { return <a className="plain-logo" href="#top"><b>Lumora</b><small>GAS, MADE VISIBLE</small></a>; }

export default function Report() {
  const [menu, setMenu] = useState(false);
  return <div className="site report" id="top"><header><Logo /><nav className={menu ? "show" : ""}>{[["Challenge", "challenge"], ["System", "system"], ["Roles", "roles"], ["Screens", "screens"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav><a className="open-app" href={appUrl}>Open working system</a><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? "Close" : "Menu"}</button></header><main>
    <section className="hero layout"><div><p className="kicker">Makerere University / Practical Skills Project</p><h1>Making LPG use <em>visible, safer,</em> and easier to plan.</h1><p className="intro">Lumora is a smart LPG monitoring and gas leakage detection system. It brings the physical cylinder, household, refill provider, and administrator into one connected workflow.</p><div className="actions"><a className="button" href="#system">Explore the system</a><a className="plain" href={appUrl}>Visit the live app</a></div></div><aside><span>PROJECT BRIEF</span><dl><div><dt>Hardware</dt><dd>ESP32, load cell, and MQ-2 sensor</dd></div><div><dt>Purpose</dt><dd>Monitor LPG levels and warn of possible leaks</dd></div><div><dt>Platform</dt><dd>Alerts, insights, and refill coordination</dd></div></dl></aside></section>
    <section id="challenge" className="section layout split"><div><p className="kicker">01 / The challenge</p><h2>When gas runs out, the problem has already arrived.</h2></div><div className="copy"><p>LPG is widely used for cooking, but the amount remaining in a cylinder is usually uncertain until the flame stops. It is an inconvenience for any household and can be particularly difficult when a refill cannot be arranged immediately.</p><p>Gas leakages create an even greater concern. Lumora is designed around early awareness: a meaningful local signal at the cylinder and a clear notification for the people responsible for it.</p></div></section>
    <section id="system" className="section dark"><div className="layout"><p className="kicker">02 / The system</p><h2>A local device and a web platform, each doing the job it is best placed to do.</h2><p className="system-copy">The device stays with the cylinder. It provides a live measurement and immediate feedback in the home. The platform makes that information accessible from elsewhere, maintains the history, and connects the household with the refill service.</p><div className="steps">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section id="roles" className="section layout"><p className="kicker">03 / People and roles</p><h2>Three workspaces. One shared source of truth.</h2><div className="roles"><article><div><span>HOUSEHOLD</span><h3>Understand and act at home.</h3></div><p>Pairs the device, monitors cylinder status, receives alerts, chooses a preferred provider, and makes manual or automatic refill requests.</p></article><article><div><span>REFILL PROVIDER / TECHNICIAN</span><h3>Turn a request into a completed refill.</h3></div><p>Receives assigned requests, reviews customer details, and progresses each refill through accepted, in transit, completed, or cancelled.</p></article><article><div><span>ADMINISTRATOR</span><h3>Keep the whole platform accountable.</h3></div><p>Manages users, cylinders and devices while monitoring open refill activity and safety conditions across Lumora.</p></article></div></section>
    <section id="screens" className="section dark"><div className="layout"><div className="screen-title"><div><p className="kicker">04 / The working platform</p><h2>Designed for the people using it.</h2></div></div><div className="all-screens">{screens.map(([label, image, title, copy]) => <figure key={label}><div><img src={image} alt={label} /></div><figcaption><span>{label}</span><h3>{title}</h3><p>{copy}</p></figcaption></figure>)}</div></div></section>
    <section className="conclusion layout"><p className="kicker">Project conclusion</p><h2>A more predictable relationship with an everyday household essential.</h2><p>Lumora combines monitoring, early safety feedback, and practical refill coordination so the household has more time to respond before an empty cylinder or possible leak becomes a crisis.</p><a className="button" href={appUrl}>Open the working Lumora system</a></section>
  </main><footer className="layout"><Logo /><span>Smart LPG Monitoring and Gas Leakage Detection System / 2026</span></footer></div>;
}
