# Generated by Django 5.2.4 on 2026-07-11 12:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Measured total cylinder weight in kilograms.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "gas_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sensor temperature in degrees Celsius.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-40")),
                            django.core.validators.MaxValueValidator(Decimal("125")),
                        ],
                    ),
                ),
                (
                    "signal_strength",
                    models.SmallIntegerField(
                        help_text="Wi-Fi RSSI in dBm.",
                        validators=[
                            django.core.validators.MinValueValidator(-120),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="devices.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(fields=["sensor", "-timestamp"], name="reading_sensor_time_idx"),
                    models.Index(fields=["timestamp"], name="reading_time_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sensor", "timestamp"), name="unique_sensor_reading_timestamp"
                    )
                ],
            },
        ),
    ]
