# Generated by Django 5.2.4 on 2026-07-13 18:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_ownership_and_cylinder_retirement"),
        ("telemetry", "0002_reading_cylinder_and_gas_leak"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepletionEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("insufficient_data", "Insufficient data"),
                            ("stale_data", "Stale data"),
                            ("failed", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("estimated_depletion_at", models.DateTimeField(blank=True, null=True)),
                ("lower_bound_at", models.DateTimeField(blank=True, null=True)),
                ("upper_bound_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_days_remaining",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=50)),
                ("input_reading_count", models.PositiveIntegerField(default=0)),
                ("input_started_at", models.DateTimeField(blank=True, null=True)),
                ("input_ended_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cylinder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depletion_estimates",
                        to="devices.cylinder",
                    ),
                ),
            ],
            options={
                "ordering": ("-generated_at",),
                "indexes": [
                    models.Index(
                        fields=["cylinder", "-generated_at"], name="depletion_cylinder_time_idx"
                    ),
                    models.Index(fields=["status"], name="depletion_status_idx"),
                ],
            },
        ),
    ]
