"use client";

import { Download, Leaf, TrendingDown } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeading } from "@/components/ui-kit";
import { usage } from "@/lib/demo-data";

const data = usage.map((value, index) => ({ day: index + 1, value }));
export default function AnalyticsPage() { return <div className="mx-auto max-w-[1180px]"><PageHeading title="Usage Analytics" subtitle="Understand household LPG usage patterns and efficiency." action={<div className="flex gap-2"><button className="btn-secondary">Last 30 Days</button><button className="btn-primary"><Download size={14} /> Export Report</button></div>} /><div className="grid gap-4 lg:grid-cols-3"><article className="card p-5"><div className="text-[11px] font-extrabold uppercase text-slate-500">Estimated Refill</div><div className="mt-5 flex items-end justify-between"><div><strong className="text-[42px] font-black text-[#d97706]">18</strong><span className="ml-2 font-bold">Days Remaining</span></div><TrendingDown className="text-orange-600" /></div><button className="mt-5 w-full rounded bg-[#f6a623] py-3 text-[12px] font-extrabold text-[#3b2500]">Schedule Refill Now</button></article><article className="card p-5"><div className="text-[11px] font-extrabold uppercase text-slate-500">Average Daily Use</div><div className="mt-8 text-[33px] font-black text-[#073b82]">1.4 <span className="text-[14px]">kg</span></div><p className="mt-2 text-[11px] font-semibold text-green-700">↓ 8% from last month</p><p className="mt-8 text-[10px] text-slate-500">Current pace supports an 18 day reserve.</p></article><article className="card border-green-300 bg-[#f3fff5] p-5"><div className="flex items-center gap-2 text-[11px] font-extrabold uppercase text-green-800"><Leaf size={15} /> Efficiency Rating</div><div className="mt-8 text-[26px] font-black text-green-800">Optimal</div><p className="mt-4 text-[11px] leading-5 text-green-900">Your usage pattern is efficient for this household.</p></article></div><section className="card mt-5 p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="section-title">Daily Consumption</h2><p className="text-[11px] text-slate-500">Gas usage over the last 30 days</p></div><span className="text-[10px] font-bold text-[#073b82]">● Usage</span></div><div className="h-[315px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid vertical={false} stroke="#e5ebf2" /><XAxis dataKey="day" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="value" fill="#073b82" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></div></section></div>; }
