"use client";
import { FormEvent, useEffect, useState } from "react";
import { PageHeading } from "@/components/ui-kit";
import { useAuth } from "@/lib/auth";
export default function SettingsPage() {
  const { user, updateProfile } = useAuth(); const [form, setForm] = useState({ username: "", phone_number: "" }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (user) setForm({ username: user.username, phone_number: user.phone_number || "" }); }, [user]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { await updateProfile(form); setMessage("Profile updated."); } catch { setMessage("The profile could not be updated."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-[760px]"><PageHeading title="Account Settings" subtitle="Your profile data from the LPG Guardian backend." /><section className="card p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="section-title">Profile</h2><p className="mt-1 text-xs text-slate-500">{user?.email}</p></div><span className={`badge ${user?.email_verified ? "badge-green" : "badge-orange"}`}>{user?.email_verified ? "Email verified" : "Verification pending"}</span></div><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><div><label className="label">Name</label><input required className="field" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></div><div><label className="label">Phone number</label><input className="field" value={form.phone_number} onChange={e => setForm({ ...form, phone_number: e.target.value })} /></div><div><label className="label">Role</label><input disabled className="field capitalize disabled:bg-slate-100" value={user?.role || ""} /></div><div><label className="label">Account status</label><input disabled className="field disabled:bg-slate-100" value={user?.is_active ? "Active" : "Inactive"} /></div><div className="sm:col-span-2 flex items-center justify-between border-t border-slate-200 pt-5"><span className={`text-xs ${message.includes("updated") ? "text-green-700" : "text-red-700"}`}>{message}</span><button disabled={saving} className="btn-primary">{saving ? "Saving…" : "Save Profile"}</button></div></form></section></div>;
}
