export type ApiList<T> = T[] | { count: number; next: string | null; previous: string | null; results: T[] };
export const rows = <T,>(data?: ApiList<T>): T[] => !data ? [] : Array.isArray(data) ? data : data.results;

export type Household = { id: number; owner: number; owner_name: string; owner_email?: string; created_at: string; updated_at: string };
export type Cylinder = { id: number; household: number; household_name: string; capacity: string; empty_weight: string; full_weight: string; latest_weight: string | null; latest_gas_percentage: string | null; latest_reading_at: string | null; installation_date: string; status: string; created_at: string; updated_at: string };
export type Sensor = { id: number; household: number | null; cylinder: number | null; esp32_id: string; mac_address: string | null; battery_level: string; online_status: boolean; is_active: boolean; last_seen: string | null; claimed_at: string | null; pairing_status: "unpaired" | "claimed" | "connected" };
export type Reading = { id: number; sensor: number; cylinder: number; esp32_id: string; message_id: string; timestamp: string; weight: string | null; gas_percentage: string | null; mq2_raw: number; mq2_ready: boolean; hx711_ok: boolean; gas_leak_detected: boolean };
export type DepletionEstimate = { id: number; cylinder: number; status: "available" | "insufficient_data" | "stale_data" | "failed"; estimated_depletion_at: string | null; lower_bound_at: string | null; upper_bound_at: string | null; estimated_days_remaining: string | null; confidence_score: string | null; input_reading_count: number; input_started_at: string | null; input_ended_at: string | null; failure_reason: string; generated_at: string; disclaimer: string };
export type Alert = { id: number; cylinder: number; reading: number; kind: "low_gas" | "empty_gas" | "gas_leak"; severity: "warning" | "critical"; title: string; message: string; is_active: boolean; resolved_at: string | null; created_at: string };
export type UserNotification = { id: number; category: "safety" | "refill" | "device" | "account"; severity: "info" | "warning" | "critical"; title: string; message: string; target_url: string; is_read: boolean; read_at: string | null; created_at: string };
export type RefillProvider = { id: number; name: string; email: string; phone_number: string };
export type RefillStatus = "pending" | "accepted" | "in_transit" | "completed" | "cancelled";
export type RefillRequest = { id: number; household: number; assigned_technician: number | null; provider: RefillProvider | null; customer: { name: string; email: string; phone: string } | null; status: RefillStatus; source: "manual" | "automatic"; requested_at: string; updated_at: string };
