# Generated by Django 5.2.4 on 2026-07-11 12:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "number_of_people",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("domestic", "Domestic"),
                            ("commercial", "Commercial"),
                            ("institutional", "Institutional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="household",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Cylinder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Usable LPG capacity in kilograms.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                    ),
                ),
                (
                    "empty_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cylinder tare weight in kilograms.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Current total cylinder weight in kilograms.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "gas_percentage",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                ("installation_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("empty", "Empty"),
                            ("disconnected", "Disconnected"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cylinders",
                        to="devices.household",
                    ),
                ),
            ],
            options={
                "ordering": ("serial_number",),
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("esp32_id", models.CharField(max_length=100, unique=True)),
                ("firmware_version", models.CharField(max_length=50)),
                (
                    "mac_address",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a MAC address in AA:BB:CC:DD:EE:FF format.",
                                regex="^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "battery_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("online_status", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cylinder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensor",
                        to="devices.cylinder",
                    ),
                ),
            ],
            options={
                "ordering": ("esp32_id",),
            },
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(fields=["usage_type"], name="household_usage_idx"),
        ),
        migrations.AddIndex(
            model_name="cylinder",
            index=models.Index(fields=["household", "status"], name="cylinder_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cylinder",
            index=models.Index(fields=["installation_date"], name="cylinder_install_idx"),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["online_status", "last_seen"], name="sensor_online_seen_idx"
            ),
        ),
    ]
